### ISSUE TITLE
An error in the usage-guide

### ISSUE THREAD

**Issue by LarsEjaas** [platypusrex/next-plugin-svgr#13]
Just a small "heads-up" to this great package.

the guide has a small error in the section that explains usage with the next-compose-plugin:

```
// next.config.js
const withPlugins = require("next-compose-plugins");
const withSvgr = require("next-svgr");

module.exports = withPlugins([
  withSvgr
  // your other plugins here
]);
```

3rd line should be changed to:

```
const withSvgr = require("next-plugin-svgr");
```

**Comment by platypusrex** [comment]
Thanks @LarsEjaas. The readme has been updated.
