### ISSUE TITLE
Invalid next.config.js options detected

### ISSUE THREAD

**Issue by Khon123** [platypusrex/next-plugin-svgr#28]
Warn  - Invalid next.config.js options detected: 
`[
  {
    "instancePath": "",
    "schemaPath": "#/additionalProperties",
    "keyword": "additionalProperties",
    "params": {
      "additionalProperty": "svgrOptions"
    },
    "message": "must NOT have additional properties"
  }
]` 

Here is my config:
`svgrOptions: {
    titleProp: false,
    icon: true,
    svgProps: {
      height: 'auto',
    },
  },`

**Comment by platypusrex** [comment]
Hi @Khon123. Honestly, it's a bit difficult to help without more detail here. Is this a warning or an error? Can you provide the entire contents of your `next.config` and `package.json`? It's definitely possible that something has changed with how the config properties are validated in new versions.

**Comment by platypusrex** [comment]
@Khon123 regression was introduced here -> https://github.com/vercel/next.js/pull/38498. Warnings have been resolved for `next-plugin-svgr` here -> https://github.com/platypusrex/next-plugin-svgr/pull/29. Update to v1.1.2 and you should be good to go.
