### ISSUE TITLE
Snyk security vulnerability issue

### ISSUE THREAD

**Issue by alex-clear** [platypusrex/next-plugin-svgr#36]
Hi Guys
We have been using your program for a long time. 
Recently we added Snyk to our project and it found vulnerability issue in you app with file-uploader lib that uses old loader-utils lib, which has security issue inside. This security issue was fixed in loader-utils lib new/latest version.
I wanted to open issue in file-uploader lib, but this lib is deprecated and archived, so maybe you can use/update in you lib diff file-uploader lib in order to fetch security vulnerability problem

<img width="1145" alt="Screen Shot 2022-11-13 at 10 23 10" src="https://user-images.githubusercontent.com/97834715/201513000-1a4623d2-c7b9-48f6-b82b-36065675a8b2.png">

Thanks

**Comment by platypusrex** [comment]
resolved in #41
