### ISSUE TITLE
Types missing from published npm package

### ISSUE THREAD

**Issue by andrejpavlovic** [platypusrex/next-plugin-svgr#44]
Looks like the `types` folder is no longer being published as part of the npm package.

https://github.com/platypusrex/next-plugin-svgr/blob/0f89730c7a2433a0719cfbfa14abc4594dc2b7cc/package.json#L15-L17

I imagine it's due to changes in this PR: https://github.com/platypusrex/next-plugin-svgr/pull/20

**Comment by platypusrex** [comment]
Thanks, @andrejpavlovic. Resolved in #45. The `types` dir is included in `v1.1.4`.
